### ISSUE TITLE
[client] Các icon trong trang tin tin chi tiết không hoạt động

### ISSUE THREAD

**Issue by giang11t1** [phanngoc/benhvien#122]
![untitled1](https://cloud.githubusercontent.com/assets/13619061/14861154/3614ebea-0cd6-11e6-831f-6ec8c27d220c.jpg)

**Comment by phanngoc** [comment]
Nút back thì Ngọc đã sửa rồi, còn cái logo Ngọc cũng chèn link rồi nhưng mà ko hiểu sao cái logo click vào nó ko chuyển trang, Ngọc nghĩ do chắc css bị đè gì đó, vẫn chưa tìm ra nguyên nhân, có gì Giang tìm hiểu thử.

**Comment by giang11t1** [comment]
Cái ni g đang muốn chia làm 2 trường hợp, Ngọc coi thấy răng rồi góp ý g vs nha.
TH1: Khi mà đang ở trang tin tức chi tiết, mình click icon logo thì nó về trang chính của bênh viện hiện tại.
chứ về trang ban đầu luôn G thấy ko ổn lắm. 
TH2 là khi đang ở trang chính của 1 bệnh viện cụt thể thì click icon logo nó sẽ về trang đầu tiên.

**Comment by phanngoc** [comment]
Uhm để Ngọc xem lại, nhưng mà cái này độ ưu tiên không cao nên mình để sau vẫn được, khi demo nhớ chú ý là được :+1:
