### ISSUE TITLE
[Client] Kiểm tra các validate cho các trường trong phần đăng kí cho đúng. Nếu đúng mới đc phép đăng kí

### ISSUE THREAD

**Issue by giang11t1** [phanngoc/benhvien#132]
Vì phần ni là chính nên g nghĩ họ bắt bẻ, N coi lại mấy cái validate cho đúng với nhá
CMND: là chuỗi số 
Email: hiện đã có hiện lên kí hiệu sai, nhưng vẫn được phép đăng kí
Địa chỉ: (Cái ni ko cần :))
Số điện thoại: Chuỗi số
Các bước tiếp theo: Nếu chọn các trường thì mới đc phép next sang trang tiếp
![untitled](https://cloud.githubusercontent.com/assets/13619061/15092900/6f820d36-14a1-11e6-8655-cd3aa2cc4220.png)

**Comment by giang11t1** [comment]
Ngọc làm phần ni thì thêm cái email ở phần Phản hồi nữa nhá
![map](https://cloud.githubusercontent.com/assets/13619061/15283221/05b4c8b6-1b73-11e6-8913-2bfdb05b3c9f.jpg)

**Comment by phanngoc** [comment]
Uhm rứa để Ngọc tạo task riêng, chứ ghi thêm vào đây khó quản lí, cái nào xong hay chưa xong cho nó rõ ràng ấy mà :)
