### ISSUE TITLE
[Client] Mã code quá dài

### ISSUE THREAD

**Issue by giang11t1** [phanngoc/benhvien#137]
![map](https://cloud.githubusercontent.com/assets/13619061/15282965/24e261e6-1b71-11e6-913f-96ba99cbe216.jpg)

**Comment by phanngoc** [comment]
Giờ Ngọc làm mã code còn 10 kí tự nhe

**Comment by giang11t1** [comment]
mới chỉ ở Client đc chứ bên Admin chưa được ở bảng Quản lý Thông Tin Khám, Với lại nếu làm đc cho mã bệnh nhân xuống còn 6 kí tự thì hay hơn :)

**Comment by phanngoc** [comment]
giờ Giang muốn Ngọc sống sao ? :D
