### ISSUE TITLE
[Client] Icon image back bị mất ảnh trong trang tin tức cho tiết.

### ISSUE THREAD

**Issue by phanngoc** [phanngoc/benhvien#40]
Check hình : http://www.awesomescreenshot.com/image/1172874/334415ec58dbb41aaf6ddded45bc09b3
Check link :
http://localhost/bv/public/index.php/news/2

**Comment by giang11t1** [comment]
@phanngoc cái ni là tùy thuộc vô Ngọc đưa hình lên chớ, giống mấy cái ảnh khác cũng đâu thấy hình,
g có chỉnh sửa lại đôi chút, Ngọc coi lại thử
