### ISSUE TITLE
[Question] Có cần thiết phải cho chỉnh sửa bệnh nhân trong admin không, hay chỉ cần để bệnh nhân tự chỉnh sửa là được rồi.

### ISSUE THREAD

**Issue by phanngoc** [phanngoc/benhvien#46]

**Comment by giang11t1** [comment]
cái ni hồi bữa g nghĩ là khi bệnh nhân chỉnh sửa, thì admin phải edit lại thông tin cho đúng. Nhưng nếu nó tự update vô database rồi hiện lên trang admin khi bệnh nhân chỉnh sửa thì ko admin ko cần chỉnh sửa nữa :D
