### ISSUE TITLE
Có link trang tạo mới phòng khám ????

### ISSUE THREAD

**Issue by giang11t1** [phanngoc/benhvien#64]
Cái button tạo mới trong trang phòng khám, g nhơ là có link đến trang tạo mới rồi, sao h ko thấy hè???
![untitled](https://cloud.githubusercontent.com/assets/13619061/14688862/e306548c-076e-11e6-961b-8f9e1e1f02b0.png)

**Comment by phanngoc** [comment]
Ủa bên Ngọc vào thấy bình thường mà, Giang check lại thử ?
