### ISSUE TITLE
[Admin] Tạo chức năng search trong admin.

### ISSUE THREAD

**Issue by phanngoc** [phanngoc/benhvien#78]
Trong các list sau:
http://localhost/bv/public/index.php/room/rooms
http://localhost/bv/public/index.php/admin/idea
http://localhost/bv/public/index.php/new/news
http://localhost/bv/public/index.php/admin/patient-info

**Comment by giang11t1** [comment]
trang "Quản lý tin tức " và "Quản lý thông tin bệnh nhân" chưa được
![map](https://cloud.githubusercontent.com/assets/13619061/15282908/ad3b8c3a-1b70-11e6-853b-97d3cfe2ec84.jpg)
