### ISSUE TITLE
[Admin] Hiển thị password trong trang thông tin cá nhân quá dài trong khi chỉ có 6 kí tự

### ISSUE THREAD

**Issue by giang11t1** [phanngoc/benhvien#80]
![untitled](https://cloud.githubusercontent.com/assets/13619061/14762283/a803fc16-09a0-11e6-9d46-332e4dfebe78.png)

**Comment by phanngoc** [comment]
Bug này ko fix nhe Giang, vì input[type="password"] phải bảo mật nên khi hiện ra nó sẽ ko hiện số kí tự, cái này là mặc định của trình duyệt rồi. Giang xem lại thử nhe :)
