### ISSUE TITLE
[Client] trong trang chỉnh sửa thông tin bệnh nhân, khi click button Update hay Bỏ qua đều xảy ra lỗi.

### ISSUE THREAD

**Issue by giang11t1** [phanngoc/benhvien#82]
![untitled](https://cloud.githubusercontent.com/assets/13619061/14762320/d7eb7c00-09a1-11e6-96b2-a9b7e9ba6a33.png)

**Comment by phanngoc** [comment]
Lỗi này bên Ngọc không bị, Giang check lại thử, xem đã cập nhật database bv9.sql chưa hoặc đã pull code mới về chưa. Nếu chắc cũng chưa được thì để mai lên Ngọc sửa :)

**Comment by giang11t1** [comment]
ukm, g có pull về vs thay db rồi mà vẫn ko đc
